### ISSUE TITLE
Add footer in the site

### ISSUE THREAD

**Issue by purnima143** [purnima143/APIU#1]

**Comment by Dheeraj-01** [comment]
Hi, can you assign me to this? Thanks :) 😊

**Comment by harikrishnajiju** [comment]
Sounds intriguing . Please let me help you with this. I have made websites with footers in them so I believe this should be easy as pie!

**Comment by js899** [comment]
Hi can you assign this to me ? I've made many websites

**Comment by js899** [comment]
Also please tell all details you need in your footer

**Comment by Dheeraj-01** [comment]
@purnima143, please assign someone to work on that??

**Comment by purnima143** [comment]
@Dheeraj-01 I assigned you for this work ( first come first serve). Others can work on unassigned issues.
