### ISSUE TITLE
Manage proper directory structure

### ISSUE THREAD

**Issue by purnima143** [purnima143/APIU#12]
All files are in a random manner.Thus,
Create a folder by name Html, JS, CSS, images and place respective files inside them.
Update the path written inside the HTML files.

**Comment by arkumari2000** [comment]
Hello, I would like to work on this issue. 
Can I work on this issue?

**Comment by purnima143** [comment]
@arkumari2000  Yes, Go ahead!!

**Comment by arkumari2000** [comment]
Thank you.

**Comment by arkumari2000** [comment]
@purnima143 Do I have to merge the files inside the web folder too?

**Comment by purnima143** [comment]
@arkumari2000 No need
