### ISSUE TITLE
Design blog page

### ISSUE THREAD

**Issue by purnima143** [purnima143/APIU#5]

**Comment by Malvika18** [comment]
can i take up this issue

**Comment by abhisheksharma09890** [comment]
I think I can easily you with this

**Comment by Malvika18** [comment]
can you explain a bit about this

**Comment by purnima143** [comment]
@Malvika18 you can work on this issue, basically, you have to follow the theme which is already present in the site. And the design of the blog page should be responsive. The remaining design part is up to your creativity.

**Comment by Malvika18** [comment]
ok thanks for the update

**Comment by OmShrivastava19** [comment]
I can also help you. I have the blog page ready with me.
